version: '3.9'

services:
  postgres:
    build: ./db/
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U=postgres -p 5432 -d db_pipelines" ]
      interval: 10s
      timeout: 5s
      retries: 10

  pipelines:
    build: ./
    ports:
        - "8000:8000"
    depends_on:
        db:
          condition: service_healthy
    container_name: pipelines_container
    environment:
      POSTGRES_DB: "db_pipeline"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./original/original.csv:./original/original.csv